// Generated by CoffeeScript 1.9.3
var onPlayerReady, onPlayerStateChange, onYouTubeIframeAPIReady, player, playing;

player = void 0;

onYouTubeIframeAPIReady = function() {
  player = new YT.Player('player', {
    playerVars: {
      controls: 0,
      showinfo: 0
    },
    videoId: 'M7lc1UVf-VE',
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
};

onPlayerReady = function() {};

onPlayerStateChange = function() {};

playing = false;

$(function() {
  var clearOverlay, click_movie_function, overlay, overlay_i, overlays, showStaticOverlay;
  overlay = $('#overlay');
  overlay_i = 0;
  clearOverlay = function() {
    overlay.css('background-image', '');
    overlay.css('height', '92%');
    overlay_i = 0;
    return playing = true;
  };
  overlays = [['', 'testCard', 150], ['contain', 'testCard2', 600], ['', 'testCard', 600]];
  showStaticOverlay = function() {
    var i;
    if (!playing) {
      if (overlay_i > overlays.length - 1) {
        overlay_i = 0;
      }
      i = overlay_i;
      overlay.css('height', '100%');
      overlay.css('background-size', overlays[i][0]);
      overlay.css('background-image', "url('img/" + overlays[i][1] + ".gif')");
      overlay_i += 1;
      return setTimeout(showStaticOverlay, overlays[i][2]);
    }
  };
  onPlayerReady = function(event) {
    clearOverlay();
    event.target.playVideo();
  };
  onPlayerStateChange = function(event) {
    if (event.data === YT.PlayerState.PLAYING) {
      return clearOverlay();
    }
  };
  click_movie_function = function() {
    playing = false;
    showStaticOverlay();
    return player.loadVideoById({
      videoId: 'bHQqvYy5KYo',
      startSeconds: 5,
      endSeconds: 7,
      suggestedQuality: 'large'
    });
  };
  return overlay[0].addEventListener('click', click_movie_function, true);
});

//# sourceMappingURL=watch.js.map
