// Generated by CoffeeScript 1.9.3
var get_video_end, get_video_start, get_video_url, iOS, if_zero_return_null, onPlayerReady, onPlayerReady2, onPlayerStateChange, onPlayerStateChange2, onYouTubeIframeAPIReady, player_index, players, ready, testCardImageBasePath, toggle_player_index, video_end, videos;

videos = window.videos;

players = [];

player_index = 0;

iOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;

ready = [false, false];

testCardImageBasePath = "https://d12gd74eaa9d1v.cloudfront.net/";

onYouTubeIframeAPIReady = function() {
  return $(function() {
    players.push(new YT.Player('player', {
      playerVars: {
        controls: 0,
        showinfo: 0,
        iv_load_policy: 3
      },
      events: {
        onReady: function() {
          return onPlayerReady();
        },
        onStateChange: function(e) {
          return onPlayerStateChange(e);
        }
      }
    }));
    return players.push(new YT.Player('player2', {
      playerVars: {
        controls: 0,
        showinfo: 0,
        iv_load_policy: 3
      },
      events: {
        onReady: function() {
          return onPlayerReady2();
        },
        onStateChange: function(e) {
          return onPlayerStateChange2(e);
        },
        onError: function(e) {
          return console.log(e);
        }
      }
    }));
  });
};

onPlayerReady = function() {
  return ready[0] = true;
};

onPlayerStateChange = function() {};

onPlayerReady2 = function() {
  return ready[1] = true;
};

onPlayerStateChange2 = function() {};

toggle_player_index = function() {
  if (player_index === 0) {
    return player_index = 1;
  } else {
    return player_index = 0;
  }
};

if_zero_return_null = function(i) {
  if (i === 0) {
    return null;
  } else {
    return i;
  }
};

get_video_url = function(videos, video_index) {
  return videos[3 * video_index];
};

get_video_start = function(videos, video_index) {
  return if_zero_return_null(videos[3 * video_index + 1]);
};

get_video_end = function(videos, video_index) {
  return if_zero_return_null(videos[3 * video_index + 2]);
};

video_end = function(container, end_splash) {
  $("body").addClass("video-done");
  $("html").addClass("video-done");
  container.hide();
  container.remove();
  end_splash.show();
  if (iOS) {
    $('.adsbygoogle').hide();
    return $('ios_code').appendTo($("head"));
  } else {
    (window.adsbygoogle || []).push({});
    return (window.adsbygoogle || []).push({});
  }
};

$(function() {
  var click_movie_function, end_splash, instructions, need_to_show_instructions, not_end_of_videos, overlay, player_html, video_index;
  instructions = $("#instructions");
  need_to_show_instructions = true;
  overlay = $('#overlay');
  end_splash = $('#end-splash');
  player_html = void 0;
  video_index = 0;
  if (iOS) {
    overlay.addClass("ios");
    instructions.addClass("ios");
    overlay.html("<span>SKIP</span>");
  }
  videos = videos.slice(1);
  not_end_of_videos = function() {
    return video_index < (videos.length / 3);
  };
  click_movie_function = function() {
    if (not_end_of_videos()) {
      if (video_index === 0) {
        players[player_index].loadVideoById({
          videoId: get_video_url(videos, video_index),
          startSeconds: get_video_start(videos, video_index),
          endSeconds: get_video_end(videos, video_index),
          suggestedQuality: 'large'
        });
      }
      player_html[player_index].css('z-index', 2);
      players[player_index].playVideo();
      toggle_player_index();
      player_html[player_index].css('z-index', 1);
      video_index += 1;
      if (not_end_of_videos()) {
        players[player_index].loadVideoById({
          videoId: get_video_url(videos, video_index),
          startSeconds: get_video_start(videos, video_index),
          endSeconds: get_video_end(videos, video_index),
          suggestedQuality: 'large'
        });
        return players[player_index].pauseVideo();
      } else {
        return players[player_index].stopVideo();
      }
    } else {
      players[0].stopVideo();
      players[1].stopVideo();
      document.onmousemove = null;
      return video_end(overlay.parent(), end_splash);
    }
  };
  onPlayerStateChange = function(event) {
    if (event.data === YT.PlayerState.PLAYING) {
      if (need_to_show_instructions && !iOS) {
        need_to_show_instructions = false;
        instructions.show();
        return instructions.fadeOut(5000);
      }
    } else if (event.data === YT.PlayerState.ENDED) {
      if (player_index === 1) {
        return click_movie_function();
      }
    }
  };
  onPlayerStateChange2 = function(event) {
    if (event.data === YT.PlayerState.ENDED) {
      if (player_index === 0) {
        return click_movie_function();
      }
    }
  };
  overlay[0].addEventListener('click', click_movie_function, true);
  if (ready[0] && ready[1]) {
    click_movie_function();
  } else {
    onPlayerReady = function() {
      ready[0] = true;
      if (ready[0] && ready[1]) {
        player_html = [$("#player"), $("#player2")];
        return click_movie_function();
      }
    };
    onPlayerReady2 = function() {
      ready[1] = true;
      if (ready[0] && ready[1]) {
        player_html = [$("#player"), $("#player2")];
        return click_movie_function();
      }
    };
  }
  return (function() {
    var cursorVisible, disappearCursor, mouseTimer;
    overlay = $("#overlay");
    mouseTimer = null;
    cursorVisible = true;
    disappearCursor = function() {
      mouseTimer = null;
      overlay.css('cursor', 'none');
      return cursorVisible = false;
    };
    return document.onmousemove = function() {
      if (mouseTimer) {
        window.clearTimeout(mouseTimer);
      }
      if (!cursorVisible) {
        overlay.css('cursor', "url('/img/forward_cursor.png') 0 0, e-resize");
        cursorVisible = true;
      }
      return mouseTimer = window.setTimeout(disappearCursor, 3000);
    };
  })();
});
